### ISSUE TITLE
.tw not work anymore

### ISSUE THREAD

**Issue by terokorp** [myano/jenni#198] opened 2015-08-04 05:43 UTC
Twitter module dosen't seems to work anymore. Every response is "Sorry, couldn't get a tweet from https://twitter.com/<name>/status/<tweetnumber> (@<name>) "

**Comment by myano** [comment] 2015-08-06 14:21
Yea, we're aware of it.

The problem is the original write up of the twitter module used HTML parsing. Which is a bad idea and sucks majorly because every time twitter slightly changes the layout of their site it would break. Basically, they started changing it a lot and making the site more and more dynamic and I gave up on keeping up with the shitty HTML parsing it was doing.

I have a local copy that uses API keys that I'm slowly trying to clean up and make public. The big downside to this is that people will need to sign up for their own twitter API keys in order for it to work and will need to put them in their config file (default.py).

**Comment by lenisko** [comment] 2015-08-06 16:26
If there is someone who can setup bot, I think that making oauth key, is not big problem for him

**Comment by myano** [comment] 2016-02-19 03:20
twitter.py has been fixed to work with oauth2 API keys that you have to request from Twitter. This was fixed in 5edcfd84bc6192f56d40c17ce41d401b553c6fd2

**Closed by myano** 2016-02-19 03:20 UTC
Labels: Bug, Medium Priority
