### ISSUE TITLE
Let the player say 'UNO' before running out of cards and punish if he's too late

### ISSUE THREAD

**Issue by JurgenNL** [myano/jenni#154] opened 2015-03-07 12:55 UTC
There is a rule in the 'real' uno what says that players have to say 'uno' before they're running out of cards. When the player says this too late, he will be punished and will have to draw two cards.
Jenni doesn't have this future and says 'uno' for the player instead. 

I think it will be good future to require a user to say 'uno' when he's going to play his last card (or when he has played his last card). When he doesn't say this, other users can punish him.

**Comment by kaneda** [comment] 2015-03-07 20:12
Duplicate of https://github.com/myano/jenni/issues/110

**Closed by kaneda** 2015-03-07 20:12 UTC
